listen="127.0.0.1:3129"
access_log="./microproxy.access.log"
activity_log="./microproxy.error.log"
allowed_connect_ports=[443, 80]
#auth_file="auth.txt"
#auth_type="basic"
#auth_realm="proxy"
forwarded_to_proxy="http_proxy=http://username:password@address:port/"
desti_proxy="http://address:port"
desti_user="username"
desti_pass="password"
forwarded_for_header="on"
allowed_networks=["127.0.0.1/32"]
add_headers=[
	["X-Test-Header1", "yes"],
	["X-Test-Header2", "no"]
]
